### ISSUE TITLE
Decide a language

### ISSUE THREAD

**Issue by AndreKurait** [KUVarsityHackers/EECS-448-Minesweeper#1]
The first step in our project is to decide a language to create minesweeper in.

**Comment by mdsvoren** [comment]
Scala.js
Pros: Nobody has ever used it.
Cons: Nobody has ever used it.

**Comment by mdsvoren** [comment]
cons: nobody has ever used it here

**Comment by AndreKurait** [comment]
C++
Pros: Everybody has experience with it

**Comment by natenichols** [comment]
Ruby on Rails
Same as Scala, but we could learn this web framework, might be more applicable than learning Scala.js, as I believe Scala is functional. 

Also we could easily do HTML/CSS/JS

As long as it's not in Python I'm cool. (pyGames)

**Comment by AndreKurait** [comment]
It has been decided!

We will use **Ruby on Rails**

Reasons for this include the following:
- server-side game logic is the best way to ensure cheating does not occur.
- It is new so it would be good for us to learn
