### ISSUE TITLE
Assign Workload

### ISSUE THREAD

**Issue by natenichols** [KUVarsityHackers/EECS-448-Minesweeper#2]
Colin-Frontend
Tiernon-Frontend

Andre-Backend (Server and Ruby on Rails API management)
Michael-Backend (Minesweeper Logic)
Nathan-Backend (Connectivity with frontend)

I have no clue about the other three of us.

**Comment by natenichols** [comment]
Y'alls should decide what you want to work on/who you want to work with

**Comment by TiernonRR** [comment]
I shall join frontend.
